BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Products" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Sources" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Product_Id"	INTEGER NOT NULL,
	"Site_link"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("Product_Id","Site_link"),
	FOREIGN KEY("Product_Id") REFERENCES "Products"("Id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Prices" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Product_Id"	INTEGER NOT NULL,
	"Date"	TEXT NOT NULL,
	"Price"	REAL,
	"Site_Id"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("Date","Product_Id"),
	FOREIGN KEY("Site_Id") REFERENCES "Sources"("Id") ON DELETE SET NULL ON UPDATE SET NULL,
	FOREIGN KEY("Product_Id") REFERENCES "Products"("Id") ON DELETE CASCADE ON UPDATE CASCADE
);
COMMIT;
