BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Sources" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Product_Id"	INTEGER NOT NULL,
	"Site_link"	TEXT NOT NULL,
	FOREIGN KEY("Product_Id") REFERENCES "Products"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("Product_Id","Site_link")
);
CREATE TABLE IF NOT EXISTS "Prices" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Product_Id"	INTEGER NOT NULL,
	"Date"	TEXT NOT NULL,
	"Price"	REAL,
	"Site_Id"	INTEGER,
	FOREIGN KEY("Product_Id") REFERENCES "Products"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("Site_Id") REFERENCES "Sources"("Id") ON DELETE SET NULL ON UPDATE SET NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("Date","Product_Id")
);
CREATE TABLE IF NOT EXISTS "Discord_webhooks" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"User_Id"	INTEGER NOT NULL UNIQUE,
	"Discord_webhook"	TEXT NOT NULL,
	FOREIGN KEY("User_Id") REFERENCES "Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Notifications" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"User_Id"	INTEGER NOT NULL UNIQUE,
	"Enabled"	INTEGER NOT NULL,
	"No_price_change_enabled"	INTEGER NOT NULL,
	FOREIGN KEY("User_Id") REFERENCES "Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Date_created"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Images" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Image_link"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Product_notifications" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Product_Id"	INTEGER NOT NULL,
	"User_Id"	INTEGER NOT NULL,
	FOREIGN KEY("User_Id") REFERENCES "Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("Product_Id") REFERENCES "Products"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("Product_Id","User_Id")
);
CREATE TABLE IF NOT EXISTS "Products" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Image"	INTEGER,
	FOREIGN KEY("Image") REFERENCES "Images"("Id") ON UPDATE CASCADE ON DELETE SET NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Emails" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"User_Id"	INTEGER NOT NULL UNIQUE,
	"Email"	TEXT NOT NULL UNIQUE,
	FOREIGN KEY("User_Id") REFERENCES "Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Admins" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"User_Id"	INTEGER NOT NULL UNIQUE,
	FOREIGN KEY("User_Id") REFERENCES "Users"("Id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
